# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-19 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180119_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('public', '\u516c\u7acb\u5b66\u6821'), ('private', '\u79c1\u4eba\u673a\u6784'), ('personal', '\u4e2a\u4eba')], default='public', max_length=100, verbose_name='\u673a\u6784\u7c7b\u522b'),
        ),
    ]
