# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-17 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180116_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='teacher/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
