# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-03 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='fav_num',
            new_name='fav_nums',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='fav_num',
            new_name='fav_nums',
        ),
    ]
