# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-17 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180117_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='des',
            new_name='desc',
        ),
    ]
