# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-18 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavorite',
            options={'verbose_name': '\u7528\u6237\u6536\u85cf', 'verbose_name_plural': '\u7528\u6237\u6536\u85cf'},
        ),
    ]
