# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-03 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180118_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.IntegerField(default=0, verbose_name='\u7528\u6237id'),
        ),
    ]
