# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-18 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20180118_1011'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='des',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='python\u540e\u7aef\u5f00\u53d1', max_length=100, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='\u8bfe\u7a0b\u673a\u6784'),
        ),
    ]
