# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-20 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_to_know',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_hint',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6559\u5e08\u63d0\u793a'),
        ),
    ]
