# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-21 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180120_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=400, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
